# Welcome to Jekyll!

title: "Wilton Aguiar"
title_separator          : "-"
logo: GH.png
name                     : "Wilton Aguiar"
description              : "Wilton Aguiar, Ph.D. student in oceanography at the Federal University of Rio Grande."
url                      : "https://willaguiar.github.io/"
show_downloads: true
google_analytics:
